// Error codes from spec Section 29, each mapped to an HTTP status.
export const ErrorCodes = {
  INVALID_SERVICE: "INVALID_SERVICE",
  ENVIRONMENT_NOT_FOUND: "ENVIRONMENT_NOT_FOUND",
  SERVICE_NOT_FOUND: "SERVICE_NOT_FOUND",
  JOB_NOT_FOUND: "JOB_NOT_FOUND",
  SERVICE_START_FAILED: "SERVICE_START_FAILED",
  SERVICE_START_TIMEOUT: "SERVICE_START_TIMEOUT",
  HEALTH_CHECK_FAILED: "HEALTH_CHECK_FAILED",
  DATABASE_RESTORE_FAILED: "DATABASE_RESTORE_FAILED",
  ORCHESTRATOR_UNAVAILABLE: "ORCHESTRATOR_UNAVAILABLE",
  ORCHESTRATOR_ROUTE_NOT_FOUND: "ORCHESTRATOR_ROUTE_NOT_FOUND",
  COMMAND_TIMEOUT: "COMMAND_TIMEOUT",
  COMMAND_FAILED: "COMMAND_FAILED",
  REPOSITORY_CLONE_FAILED: "REPOSITORY_CLONE_FAILED",
  REPOSITORY_NOT_CONFIGURED: "REPOSITORY_NOT_CONFIGURED",
  IMAGE_BUILD_FAILED: "IMAGE_BUILD_FAILED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNSUPPORTED_DATABASE_ENGINE: "UNSUPPORTED_DATABASE_ENGINE",
  DATABASE_QUERY_FAILED: "DATABASE_QUERY_FAILED",
  SERVICE_REPO_NOT_FOUND: "SERVICE_REPO_NOT_FOUND",
  AIDER_FAILED: "AIDER_FAILED",
  AIDER_TIMEOUT: "AIDER_TIMEOUT"
};

const STATUS_BY_CODE = {
  [ErrorCodes.INVALID_SERVICE]: 400,
  [ErrorCodes.ENVIRONMENT_NOT_FOUND]: 404,
  [ErrorCodes.SERVICE_NOT_FOUND]: 404,
  [ErrorCodes.JOB_NOT_FOUND]: 404,
  [ErrorCodes.SERVICE_START_FAILED]: 502,
  [ErrorCodes.SERVICE_START_TIMEOUT]: 504,
  [ErrorCodes.HEALTH_CHECK_FAILED]: 502,
  [ErrorCodes.DATABASE_RESTORE_FAILED]: 502,
  [ErrorCodes.ORCHESTRATOR_UNAVAILABLE]: 502,
  [ErrorCodes.ORCHESTRATOR_ROUTE_NOT_FOUND]: 404,
  [ErrorCodes.COMMAND_TIMEOUT]: 504,
  [ErrorCodes.COMMAND_FAILED]: 502,
  [ErrorCodes.REPOSITORY_CLONE_FAILED]: 502,
  [ErrorCodes.REPOSITORY_NOT_CONFIGURED]: 400,
  [ErrorCodes.IMAGE_BUILD_FAILED]: 502,
  [ErrorCodes.VALIDATION_ERROR]: 400,
  [ErrorCodes.UNSUPPORTED_DATABASE_ENGINE]: 400,
  [ErrorCodes.DATABASE_QUERY_FAILED]: 502,
  [ErrorCodes.SERVICE_REPO_NOT_FOUND]: 404,
  [ErrorCodes.AIDER_FAILED]: 502,
  [ErrorCodes.AIDER_TIMEOUT]: 504
};

export class AppError extends Error {
  constructor(code, message, details = {}) {
    super(message);
    this.name = "AppError";
    this.code = code;
    this.statusCode = STATUS_BY_CODE[code] || 500;
    this.details = details;
  }

  toJSON() {
    return { error: { code: this.code, message: this.message, ...this.details } };
  }
}

export function appError(code, message, details = {}) {
  return new AppError(code, message, details);
}
